### ISSUE TITLE
Link to "Gitmoji commit standards" in README.md gives 404

### ISSUE THREAD

**Issue by jakkdl** [apartresearch/deepdecipher#146]
https://github.com/apartresearch/deepdecipher?tab=readme-ov-file#repo-standards

gives a link to https://github.com/apartresearch/deepdecipher/blob/main/gitmoji.dev

but that file does not exist, giving an error: 404

**Comment by albertsgarde** [comment]
Fixed in #147

**Comment by jakkdl** [comment]
🚀
